# Generated by Django 5.1.6 on 2025-07-21 07:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_permission', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of allowed modules or ['all'] for full access.", size=None)),
                ('user_role_module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rolemaster')),
            ],
        ),
    ]
