# Generated by Django 5.1.6 on 2025-07-23 11:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermaster_city_usermaster_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='user_image',
            field=models.ImageField(blank=True, default=accounts.models.default_user_image_path, null=True, upload_to='user_images/'),
        ),
    ]
